### ISSUE TITLE
Quantitative or Qualitative Elbow Method

### ISSUE THREAD

**Issue by hobson** [Mathemilda/Numeric_ElbowMethod_For_K-means#1]
Are you recommending a quantitative metric for calculating the location (K value) of the _elbow_ or are you suggesting a particular approach to visually examining plots in order to qualitatively identify the location (K value) of the _elbow_?  It's my understanding that the visual qualitative method is not a mathematical object, but simply a visualization tool for exploring data. For most real world noisy data, there will not be any falsifiable hypothesis that you can test that involves the use of the qualitative _elbow method_ and there's no P-value that you can use to determine the statistical significance of any particular K-value chosen by visual inspection of a chart.

**Comment by Mathemilda** [comment]
Hello Hobson,
In general clustering combines quantitative and qualitative evaluations.
In practice clustering always done with a goal to learn realistic insights about data structure, and this is a qualitative part of clustering. It comes after qualitative part when we define the number of clusters, although the qualitative part is a priority. In particular we may choose clustering which is not the best geometrically but it makes the most sense for business/research objective. 
In my case data are abstract and randomly generated.  As for a P-value then in Statistics it is computed when we know a formula for variable distributions. In my examples the resulting distributions do not look like standard known distributions, and I assume that in general it happens more often than not. Nevertheless we still can approximate P-value using bootstrapping methods, although they are likely to be rather time-consuming.

**Comment by Mathemilda** [comment]
There were no other questions from anybody.
